// <auto-generated />
using System;
using GoldCS.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldCS.Infraestructure.Migrations.GoldResourcesDb
{
    [DbContext(typeof(GoldResourcesDbContext))]
    [Migration("20251024224454_AddNewColumnsCategoryTable")]
    partial class AddNewColumnsCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdressType")
                        .HasColumnType("integer");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Complemento")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UF")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Adresses", (string)null);
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Linha completa de colchões de solteiro, casal e queen/king size",
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4570),
                            Name = "Colchões"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Travesseiros de espuma, látex, viscoelástico e anatômicos",
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4587),
                            Name = "Travesseiros"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Lençóis, fronhas, edredons e protetores de colchão",
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4588),
                            Name = "Roupa de Cama"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Cabeceiras, mesas de cabeceira e guarda-roupas",
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4589),
                            Name = "Móveis de Quarto"
                        });
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellPhone = "11912345678",
                            Cpf = "12345678901",
                            Email = "joao.silva@example.com",
                            Name = "João Silva",
                            Phone = "1132345678",
                            RegisterDate = new DateTime(2025, 10, 24, 22, 44, 53, 651, DateTimeKind.Utc).AddTicks(4318)
                        },
                        new
                        {
                            Id = 2,
                            CellPhone = "21998765432",
                            Cpf = "98765432100",
                            Email = "maria.oliveira@example.com",
                            Name = "Maria Oliveira",
                            Phone = "2134567890",
                            RegisterDate = new DateTime(2025, 10, 24, 22, 44, 53, 651, DateTimeKind.Utc).AddTicks(4322)
                        });
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdressId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdressId");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<double>("UnitaryValue")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts", (string)null);
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("MeasureType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CategoryId = 1,
                            CostPrice = 1200.00m,
                            Description = "Colchão de casal ortopédico com molas ensacadas",
                            Height = 25.0m,
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4795),
                            MeasureType = "cm",
                            Name = "Colchão Casal Ortobom",
                            Stock = 15,
                            Width = 138.0m
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CategoryId = 1,
                            CostPrice = 2200.00m,
                            Description = "Colchão queen size com camada de viscoelástico para maior conforto",
                            Height = 30.0m,
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4803),
                            MeasureType = "cm",
                            Name = "Colchão Queen Viscoelástico",
                            Stock = 10,
                            Width = 158.0m
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CategoryId = 2,
                            CostPrice = 180.00m,
                            Description = "Travesseiro viscoelástico com memória, tecnologia NASA",
                            Height = 15.0m,
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4804),
                            MeasureType = "cm",
                            Name = "Travesseiro NASA",
                            Stock = 50,
                            Width = 60.0m
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CategoryId = 3,
                            CostPrice = 350.00m,
                            Description = "Lençol 300 fios algodão egípcio com fronhas inclusas",
                            Height = 0.5m,
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4806),
                            MeasureType = "cm",
                            Name = "Jogo de Lençol Casal 300 fios",
                            Stock = 40,
                            Width = 200.0m
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CategoryId = 4,
                            CostPrice = 900.00m,
                            Description = "Cabeceira estofada para cama queen, acabamento em linho",
                            Height = 120.0m,
                            InclusionDate = new DateTime(2025, 10, 24, 19, 44, 53, 651, DateTimeKind.Local).AddTicks(4808),
                            MeasureType = "cm",
                            Name = "Cabeceira Estofada Queen",
                            Stock = 8,
                            Width = 160.0m
                        });
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Adress", b =>
                {
                    b.HasOne("GoldCS.Domain.Models.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Order", b =>
                {
                    b.HasOne("GoldCS.Domain.Models.Entities.Adress", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressId");

                    b.HasOne("GoldCS.Domain.Models.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Adress");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.OrderProduct", b =>
                {
                    b.HasOne("GoldCS.Domain.Models.Entities.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoldCS.Domain.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Product", b =>
                {
                    b.HasOne("GoldCS.Domain.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GoldCS.Domain.Models.Entities.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
