// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src.Data;

#nullable disable

namespace GoldCSAPI.Migrations
{
    [DbContext(typeof(GoldCSDBContext))]
    [Migration("20230531233036_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Entities.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientID"));

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LandlinePhone")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ClientID");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("tb_clients", (string)null);
                });

            modelBuilder.Entity("src.Models.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressID"));

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("AddressID");

                    b.HasIndex("Cep")
                        .IsUnique();

                    b.ToTable("tb_address", (string)null);
                });

            modelBuilder.Entity("src.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("CategoryID");

                    b.ToTable("tb_categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Colchão"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Cama"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Travesseiro"
                        },
                        new
                        {
                            CategoryID = 4,
                            Name = "Outros"
                        },
                        new
                        {
                            CategoryID = 5,
                            Name = "Base / Baú"
                        },
                        new
                        {
                            CategoryID = 6,
                            Name = "Cabeceira"
                        });
                });

            modelBuilder.Entity("src.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<int>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeliveryForecast")
                        .HasColumnType("date");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("OrderID");

                    b.HasIndex("AddressID");

                    b.HasIndex("ClientID");

                    b.HasIndex("UserID");

                    b.ToTable("tb_order", (string)null);
                });

            modelBuilder.Entity("src.Models.Entities.OrderProduct", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductID", "OrderID");

                    b.HasIndex("OrderID");

                    b.ToTable("tb_order_product", (string)null);
                });

            modelBuilder.Entity("src.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("tb_products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 5,
                            Name = "Baú casal Blidado",
                            Price = 890m,
                            Quantity = 10,
                            Version = "1.38 x 1.88"
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 6,
                            Name = "Cabeceira Queen",
                            Price = 390m,
                            Quantity = 100,
                            Version = "1.58"
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Name = "Colchão ProRelax Opala",
                            Price = 1500m,
                            Quantity = 10,
                            Version = "1.38 x 1.88 x 24cm"
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 3,
                            Name = "Travesseiro Nasa DualFlex",
                            Price = 150m,
                            Quantity = 20,
                            Version = "16cm"
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 3,
                            Name = "Travesseiro Cervical",
                            Price = 160m,
                            Quantity = 50,
                            Version = "-"
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Name = "Colchão SanKonfort Le Griff",
                            Price = 2400m,
                            Quantity = 200,
                            Version = "1.38 x 188 x 33cm"
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 1,
                            Name = "Colchão SanKonfort Le Griff",
                            Price = 2990m,
                            Quantity = 30,
                            Version = "1.58 x 198 x 33cm"
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 1,
                            Name = "Colchão SanKonfort Le Griff",
                            Price = 3200m,
                            Quantity = 90,
                            Version = "1.93 x 203 x 33cm "
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            Name = "Cama Bedrom Andressa Avelã",
                            Price = 2300m,
                            Quantity = 60,
                            Version = "1.38 x 188"
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 1,
                            Name = "Colchão ProRelax Pro Hotel",
                            Price = 1500m,
                            Quantity = 70,
                            Version = "1.38 x 188 x 28cm"
                        });
                });

            modelBuilder.Entity("src.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserID");

                    b.ToTable("tb_users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 3,
                            Active = true,
                            Email = "franchesco@gmail.com",
                            Name = "Franchesco legal",
                            Password = "$2a$12$vHinXxf4yXtBDfGY6rVpae0VrQ2UladDGL4VydcbrwUd.sj4yY3sy",
                            Role = "admin"
                        },
                        new
                        {
                            UserID = 4,
                            Active = true,
                            Email = "jones@gmail.com",
                            Name = "Jones legal",
                            Password = "$2a$12$vHinXxf4yXtBDfGY6rVpae0VrQ2UladDGL4VydcbrwUd.sj4yY3sy",
                            Role = "seller"
                        });
                });

            modelBuilder.Entity("src.Models.Entities.Order", b =>
                {
                    b.HasOne("src.Models.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Entities.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("src.Models.Entities.OrderProduct", b =>
                {
                    b.HasOne("src.Models.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("src.Models.Entities.Product", b =>
                {
                    b.HasOne("src.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("src.Entities.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("src.Models.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("src.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("src.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("src.Models.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("src.Models.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
